# Generated by Django 2.2.5 on 2019-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoistKarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_karma', models.IntegerField()),
                ('total_karma', models.IntegerField()),
                ('current_daily_steak', models.IntegerField()),
                ('current_weekly_steak', models.IntegerField()),
            ],
        ),
    ]
