# Generated by Django 2.2.6 on 2019-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoistkarma',
            name='current_daily_steak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='current_weekly_steak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='new_karma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='total_karma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
