# Generated by Django 2.2.5 on 2019-10-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20191014_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoistkarma',
            old_name='current_daily_steak',
            new_name='current_daily_streak',
        ),
        migrations.RenameField(
            model_name='todoistkarma',
            old_name='current_weekly_steak',
            new_name='current_weekly_streak',
        ),
    ]
