# Generated by Django 2.2.6 on 2019-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_auto_20191017_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoistkarma',
            options={'ordering': ['date']},
        ),
    ]
