# Generated by Django 2.2.6 on 2019-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_auto_20191017_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoistkarma',
            name='current_daily_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='current_weekly_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='new_karma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todoistkarma',
            name='total_karma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
