# Generated by Django 2.2.5 on 2019-11-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_auto_20191019_1953'),
        ('productivity', '0005_auto_20191101_2220'),
    ]

    operations = [
    ]
