# Generated by Django 2.2.6 on 2019-11-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_auto_20191102_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['category', 'created_at']},
        ),
    ]
