# Generated by Django 2.2.6 on 2020-01-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0010_auto_20191103_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
