# Generated by Django 2.2.7 on 2019-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0010_auto_20191103_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
