# Generated by Django 2.2.6 on 2020-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0011_auto_20200108_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('thread_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
