# Generated by Django 2.2.7 on 2020-02-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0012_gmail'),
        ('productivity', '0011_auto_20191114_1627'),
    ]

    operations = [
    ]
