# Generated by Django 2.2.6 on 2020-05-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0013_merge_20200209_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAddonProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=8)),
                ('base_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.TaskAddonProvider')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.Task')),
            ],
        ),
    ]
