# Generated by Django 2.2.6 on 2020-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0014_taskaddon_taskaddonprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskaddon',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
