# Generated by Django 2.2.6 on 2020-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0015_auto_20200525_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskaddonprovider',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
