# Generated by Django 3.0.7 on 2020-06-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0016_taskaddonprovider_shortcut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoistKarma',
        ),
    ]
