# Generated by Django 3.0.7 on 2020-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0017_delete_todoistkarma'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='todoist_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='todoist_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
