# Generated by Django 3.1.2 on 2020-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0018_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=400),
        ),
    ]
