# Generated by Django 3.0.7 on 2020-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0019_category_todoist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='todoist_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
