# Generated by Django 3.0.7 on 2020-08-03 08:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0021_auto_20200730_2008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('todoist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('todoist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('todoist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
