# Generated by Django 3.0.7 on 2020-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0022_auto_20200803_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='todoist_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='todoist_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=400, unique=False),
        ),
    ]
