# Generated by Django 3.1.2 on 2021-01-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0025_auto_20200804_1028'),
        ('productivity', '0019_auto_20201209_1819'),
    ]

    operations = [
    ]
