# Generated by Django 3.1.7 on 2021-03-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0026_merge_20210111_1903'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
