# Generated by Django 3.2.1 on 2021-05-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0027_auto_20210308_1934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
