# Generated by Django 3.2.5 on 2021-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0028_alter_project_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
