# Generated by Django 3.2.5 on 2021-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_pullrequest_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='task_created',
            field=models.BooleanField(default=False),
        ),
    ]
