# Generated by Django 2.2.5 on 2019-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20, unique=True)),
                ('total_size', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('total_files', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('log', models.FileField(upload_to='')),
            ],
        ),
    ]
