# Generated by Django 2.2.5 on 2019-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
