# Generated by Django 2.2.5 on 2019-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20190920_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='app',
            field=models.CharField(max_length=20),
        ),
    ]
