# Generated by Django 2.2.5 on 2019-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20190920_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
