# Generated by Django 2.2.5 on 2019-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20190920_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='log',
            field=models.URLField(),
        ),
    ]
