# Generated by Django 2.2.6 on 2020-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20200212_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
