# Generated by Django 2.2.6 on 2020-02-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_pullrequest_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('number', 'repo_name')},
        ),
    ]
