# Generated by Django 3.2.1 on 2021-05-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_repository_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ['-created_at']},
        ),
    ]
