# Generated by Django 3.2.1 on 2021-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_backup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
