# Generated by Django 3.2.1 on 2021-05-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0028_alter_project_managers'),
        ('logs', '0013_repository_watch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ('-watch', 'name')},
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.project'),
        ),
    ]
