# Generated by Django 3.2.5 on 2021-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_auto_20210518_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PullRequest',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
